document.documentElement.classList.add('js');
const navToggle=document.querySelector('.menu-toggle'),nav=document.getElementById('global-menu');
navToggle?.addEventListener('click',()=>{const open=navToggle.getAttribute('aria-expanded')!=='true';navToggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&navToggle?.getAttribute('aria-expanded')==='true'){navToggle.setAttribute('aria-expanded','false');nav.classList.remove('open');navToggle.focus()}});
const services={
announce:{label:'アナウンス',eyebrow:'ANNOUNCE / VOICE WORK',title:['聞いて引き出す','声で届ける'],description:'インタビューを中心に、司会・ナレーションも。届けたい内容と、その場に合う声や進め方をご相談ください。',note:'用途・希望時期・企画の状況からお聞かせください。',action:'声の仕事を見る',href:'work.html'},
coaching:{label:'コーチング',eyebrow:'COACHING / INDIVIDUAL & TEAM',title:['自分のこれから','チームのこれから'],description:'個人やチームの悩み・目標を対話で整理し、次の一歩を考えるコーチング。',note:'対面・オンラインに対応。目標とご希望に合わせて、内容と料金を個別にご相談いただけます。',action:'コーチングを見る',href:'dialogue.html#coaching'},
kids:{label:'KIDS',eyebrow:'KIDS / PROGRAM CONCEPT',title:['自分で考え','人と関わり 伝える力を'],description:'インタビューを通じて、自分で考え、人と関わり、伝える力を育む。これから社会で生きていくために大切な経験を重ねるプログラムを目指しています。',note:'構想段階です。募集・対象年齢・日時・会場・料金は未確定です。',action:'体験の構想を見る',href:'dialogue.html#kids'},
thankyou:{label:'Thank you Celebration',eyebrow:'THANK YOU CELEBRATION / ご案内準備中',title:['ありがとうを','今 伝える時間'],description:'大切な人に感謝を伝える会を、どのようにお手伝いするか。Thank you Celebrationは、生前葬をテーマにした活動です。詳しい内容は準備中です。',note:'開催形式・支援範囲・料金・受付は未確定です。',action:'準備状況を見る',href:'dialogue.html#thankyou'},
training:{label:'講演・研修',eyebrow:'TALKS & TRAINING',title:['話す 聞く 伝えるを','学びの時間に'],description:'インタビューや司会の経験を活かした、聞き方・伝え方の講演・研修。テーマや対象に合わせて、内容をご相談いただけます。',note:'仮の説明です。具体的なテーマや事例は、中願寺さん確認待ちです。',action:'講演・研修を見る',href:'work.html#training'}
};
const buttons=[...document.querySelectorAll('[data-service]')];
const title=document.getElementById('content-title'),label=document.getElementById('content-label'),description=document.getElementById('content-description'),note=document.getElementById('content-note'),action=document.getElementById('content-action'),reset=document.getElementById('reset'),selection=document.getElementById('selection-label');
if(title){
const initial={title:title.innerHTML,label:label.textContent,description:description.textContent,note:note.textContent,action:action.innerHTML,href:action.getAttribute('href')};
function show(id){const data=services[id];if(!data)return;for(const b of buttons)b.setAttribute('aria-pressed',String(b.dataset.service===id));title.replaceChildren();data.title.forEach((line,i)=>{if(i)title.append(document.createElement('br'));title.append(document.createTextNode(line))});label.textContent=data.eyebrow;description.textContent=data.description;note.textContent=data.note;action.textContent=data.action+' ↗';action.href=data.href;reset.hidden=false;selection.textContent=data.label+'を表示中';document.getElementById('category-portrait').dataset.category=id;document.getElementById('portrait-category').textContent=data.label;const imageScenes={"announce": ["interview-scene-ai-v1.png", "インタビューで相手の話を聞く場面"], "coaching": ["coaching-scene-ai-v1.png", "一対一で対話をする場面"], "kids": ["kids-interview-ai-v2.png", "子どもの質問に耳を傾ける場面"], "thankyou": ["thankyou-scene-ai-v1.png", "大切な人との感謝や交流を支える場面"], "training": ["training-scene-ai-v1.png", "研修で参加者の質問に応じる場面"]};const sceneImage=document.getElementById('hero-scene-image');sceneImage.src='assets/'+imageScenes[id][0];sceneImage.alt=imageScenes[id][1]+'を描いたAI生成イメージ';}
for(const b of buttons){b.addEventListener('click',()=>show(b.dataset.service));b.addEventListener('keydown',e=>{let i=buttons.indexOf(b);if(e.key==='ArrowRight')i=(i+1)%buttons.length;else if(e.key==='ArrowLeft')i=(i-1+buttons.length)%buttons.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=buttons.length-1;else return;e.preventDefault();buttons[i].focus({preventScroll:true});show(buttons[i].dataset.service)})}
reset.addEventListener('click',()=>{buttons.forEach(b=>b.setAttribute('aria-pressed','false'));title.innerHTML=initial.title;label.textContent=initial.label;description.textContent=initial.description;note.textContent=initial.note;action.innerHTML=initial.action;action.setAttribute('href',initial.href);reset.hidden=true;selection.textContent='5つの活動をご紹介します';document.getElementById('category-portrait').dataset.category='overview';document.getElementById('portrait-category').textContent='VOICE · WORDS · WONDER';buttons[0].focus({preventScroll:true})});
}
const inquiryTopics={interview:'インタビュー',mc:'司会・MC',narration:'ナレーション',training:'講演・研修',coaching:'コーチング'};
const topic=new URLSearchParams(location.search).get('category');
if(document.getElementById('request-topic')&&inquiryTopics[topic]){document.getElementById('request-topic').textContent=inquiryTopics[topic]+'について、目的や希望時期をお知らせください。';document.querySelector('a[href^="mailto:"]').href='mailto:chuganjikaori@gmail.com?subject='+encodeURIComponent('MAKE WONDER '+inquiryTopics[topic]+'のご相談')}
